### ISSUE TITLE
X-axis scale issue when using "free_x" with `facet_ragged_cols()`

### ISSUE THREAD

**Issue by mattwarkentin** [mikmart/ggragged#2]
Hi @mikmart,

Really neat package. I think I might've found a bug with how the "free" scales work. See the examples below. 

This is not a very exciting example, but I think it demonstrates the issue. The first image is correct.

When using `scales = "free_x"` in this second image, the x-axis scale does become free, but the labels are wrong. The two panels on the right have bars with the values `6` and `22` but the x-axis labels are the same as for the left-side panels. Hopefully that makes sense.
``` r
library(tidyverse)
library(ggplot2)
library(ggragged)

df <- tribble(
  ~name, ~var1, ~var2, ~value,
  'John', 'A', 'X', 5,
  'Paul', 'A', 'Y', 6,
  'Ringo', 'B', 'X', 20,
  'George', 'B', 'Y', 22,
  'Elton', 'C', 'X', 50
) 

df |> 
  ggplot(aes(name, value)) +
  geom_col() +
  coord_flip() +
  facet_ragged_cols(vars(var1), vars(var2))
```

![](https://i.imgur.com/mHw67Nu.png)

``` r

df |> 
  ggplot(aes(name, value)) +
  geom_col() +
  coord_flip() +
  facet_ragged_cols(vars(var1), vars(var2), scales = 'free_x')
```

![](https://i.imgur.com/W7UOCyK.png)

**Comment by mattwarkentin** [comment]
The issue seems to be with `coord_flip()`. The issue goes away if you don't flip the coordinates and just flip the variables in `aes()`.
``` r
library(tidyverse)
library(ggplot2)
library(ggragged)

df <- tribble(
  ~name, ~var1, ~var2, ~value,
  'John', 'A', 'X', 5,
  'Paul', 'A', 'Y', 6,
  'Ringo', 'B', 'X', 20,
  'George', 'B', 'Y', 22,
  'Elton', 'C', 'X', 50
) 

df |> 
  ggplot(aes(value, name)) +
  geom_col() +
  facet_ragged_cols(vars(var1), vars(var2))
```

![](https://i.imgur.com/rqDVS8D.png)

``` r

df |> 
  ggplot(aes(value, name)) +
  geom_col() +
  facet_ragged_cols(vars(var1), vars(var2), scales = 'free_x')
```

![](https://i.imgur.com/nxUD8fZ.png)

**Comment by mikmart** [comment]
Thanks for the report and additional diagnosis!

**Comment by mikmart** [comment]
Turns out this would be most naturally fixed by a change in ggplot2 which I've suggested. Let's see how that goes.

**Comment by mikmart** [comment]
@mattwarkentin this should now be fixed by installing the development version of either ggplot2 or ggragged.

**Comment by mattwarkentin** [comment]
Wow, thanks so much for addressing this so quickly! Great work.
